### ISSUE TITLE
Gestion des Row-Level Security

### ISSUE THREAD

**Issue by jdlom** [MTES-MCT/asgard-postgresql#1]
Bonsoir,
je n'ai pas encore pris le temps de tester l'extension
mais en tous les cas c'est évident qu'elle va permettre de démocratiser postgreSQL.

Envisagez-vous d'ajouter des fonctionnalités pour faciliter la configuration de RLS ?
Je pense que beaucoup de services seraient très intéressés par cela et peu de gens savent que c'est réalisable.

A bientôt,
JDL

**Comment by alhyss** [comment]
Bonjour @jdlom

Nous n'y avons pas encore réfléchi à ce stade, pour être honnête. L'idée de base d'ASGARD était plutôt de proposer un mécanisme simplifié pour définir des droits homogènes dans chaque schéma, les fonctionnalités natives de PostgreSQL restant disponibles pour des permissions plus raffinées. Ceci dit, rien n'empêcherait de proposer des fonctions utilitaires pour faciliter l'implémentation des _row level policies_, s'il y a des besoins spécifiques.

As-tu des idées précises à ce sujet ?

Quoi qu'il en soit, je note qu'il serait utile de dire un mot des _row level policies_ dans la documentation, ne serait-ce que pour rappeler que ça existe.

**Comment by jdlom** [comment]
> As-tu des idées précises à ce sujet ?

Je t'avoue ne pas encore y avoir réfléchi ;-) 
Je jette juste le pavé dans la mare. Plus sérieusement, j'ai ouvert l'issue pour que vous ayez cela sous le coude si vous avez envie de faire évoluer l'extension. Je suis conscient que ce ne soit pas prioritaire.

> Ceci dit, rien n'empêcherait de proposer des fonctions utilitaires pour faciliter l'implémentation des row level policies, s'il y a des besoins spécifiques.

Je pense en effet que c'est une excellente idée car cette fonctionnalité est vraiment méconnue. Cela soulèvera peut-être des besoins, et  il sera alors temps,  si vous le souhaitez, de  réfléchir à l'intégration dans Asgard.

Quoiqu'il en soit, je vais d'abord tester l'extension et me plonger dans le code.

**Comment by alhyss** [comment]
Ok ! Pour l'heure, je note au moins d'ajouter un mot sur les _row level policies_ au point II.5 de la documentation - "Compatibilité avec les mécanismes usuels de gestion des droits" - vu que c'est un "mécanisme usuel de gestion de droits" et qu'il ne coûte pas grand chose de signaler son existence.

**Comment by alhyss** [comment]
_La nouvelle documentation web publiée parallèlement à la version 1.2.3 comporte un [point sur les politiques de sécurité](https://snum.scenari-community.org/Asgard/Documentation/#SEC_Compatibilite:kuyhHItLLBicVTWQN7ZgGf)._

**Comment by jdlom** [comment]
J'ai lu. Impeccable !
