### ISSUE TITLE
Problème de droits sur nouvelle base postgresql

### ISSUE THREAD

**Issue by thiegaillard** [MTES-MCT/asgard-postgresql#10]
je suis en train de finaliser les droits sur notre nouvelle base PostgreSQL et j'ai un problème de droit que je ne comprend pas.
On a créé les droits avec Asgard Manager et, en regardant dans Asgard Manager, un compte thierry_test a des droits sur les schémas r_ mais quand je rentre sur le schéma avec PostgreSQL avec ce compte, impossible d'afficher les données
Dans le sql, j'ai des droits contradictoires avec r_lecture

REVOKE ALL ON TABLE r_mobilites_pro.fd_mob_pro_fr_2007 FROM r_lecture;
GRANT ALL ON TABLE r_mobilites_pro.fd_mob_pro_fr_2007 TO groupe_adl;
GRANT SELECT ON TABLE r_mobilites_pro.fd_mob_pro_fr_2007 TO r_lecture;

Il y a peut-être une chose que je n'ai pas compris.

**Comment by alhyss** [comment]
Est-ce que tu peux lancer un diagnostic des droits ?

Avec Asgard Manager (potentiellement assez long, car l'ensemble de la base est examiné), c'est via le menu _[Gestion de la base](https://snum.scenari-community.org/Asgard/Documentation/co/SEC_MenuGestionBase.html) > Rechercher les anomalies_. Si Asgard identifie des droits qui ne correspondent pas à ce qui est normalement prévu pour les producteurs, éditeurs et lecteurs des schémas, ces "anomalies" seront listées dans l'[onglet _Diagnostics_](https://snum.scenari-community.org/Asgard/Documentation/co/SEC_OngletDiagnostics.html).

Tu peux aussi passer par une commande SQL, avec dans ce cas la possibilité de ne scanner que le ou les schémas qui t'intéressent (ou sans paramètre pour scanner tout). 

```sql
SELECT * FROM z_asgard_admin.asgard_diagnostic(ARRAY['r_lecture']) ;
```

Pour plus de détails sur ce qui est considéré comme anomalie et l'interprétation du résultat, tu peux te référer à [cette page](https://snum.scenari-community.org/Asgard/Documentation/co/CON_AsgardDiagnostic.html) de la documentation. La démarche générale de résolution des problèmes est décrite dans [cette partie](https://snum.scenari-community.org/Asgard/Documentation/co/SEC_ResolutionDesProblemes.html).

Si tu n'as aucune anomalie, alors j'aurais besoin de savoir quels sont les rôles producteur, éditeur et lecteur du schéma et quelles permissions ton rôle `thierry_test` a sur ces rôles, le cas échéant par héritage.

**Comment by thiegaillard** [comment]
J'ai eu ce truc bizarre mais finalement ça fonctionne.
Aujourd'hui, les utilisateurs devaient basculer sur ce nouveau serveur mais il y a un problème réseau à Créteil aujourd'hui !
On ne peut rien faire en ce moment.
Mais je pense que l'on a compris la gestion des droits.
Je passerai quand même le diagnostique demain.

Notre nouveau serveur PostgreSQL 12 est bien doté : 8 cœurs 32 Go RAM - 2 To DD
une base principale de 500 Go asgardisée
une base archive de 90 Go
+ 3 autres bases de 100 Go à asgardiser

Merci de ton aide.

**Comment by alhyss** [comment]
Ok ! Tiens-moi au courant.
