### ISSUE TITLE
Documentation indisponible

### ISSUE THREAD

**Issue by Nicolas-REMOND** [MTES-MCT/asgard-postgresql#16]
Le lien indiqué pour la documentation https://snum.scenari-community.org/Asgard/Documentation abouti  à une page err 404

**Comment by alhyss** [comment]
Merci pour le signalement @Nicolas-REMOND. Nous sommes en train de chercher l'origine du problème afin de rétablir l'accès au plus vite.

**Comment by alhyss** [comment]
Le site est de nouveau opérationnel depuis la semaine dernière.
