### ISSUE TITLE
Etat de maturité du projet ?

### ISSUE THREAD

**Issue by MarHoff** [MTES-MCT/asgard-postgresql#3]
Bonjour et tout d'abord merci d'avoir rendu cette extension publique!

J'ai une problématique de réaffectation de droits d'usages d'un role à un autre sur ma base de production c'est pourquoi votre projet découvert un peu par hasard (en regardant du coté de  SG5-SYMBOLISATION) à attiré mon attention.

Je vous ai fait une suggestion dans un autre ticket https://github.com/MTES-MCT/asgard-postgresql/issues/2 mais j'ai plusieurs questions plus globales que je me permet de vous poser:

- Pensez-vous que l'extension est assez mature pour être déployée chez des tiers ou considérez vous l'extension comme trop expérimentale/instable à ce stade?
- Quel serait l'impact en cas déploiement sur une base existante et disposant déjà de rôles en place?
- Quel est l'impact en cas de désinstallation si un retour à une gestion plus manuelle est finalement préférable?
- Typiquement mon cas d'usage correspondrait à un besoin de "mise au propre" de la gestion des droits sur une base qui s'est construite progressivement en 10 ans avec des droits gérés +/- manuellement. Est-ce que asgard-postgresql vous semble adapté à ce type démarche?

Merci dans tout les cas pour le gros travail réalisé dans ce repo!

PS: Désolé je découvre seulement maintenant [cette partie de la doc](https://snum.scenari-community.org/Asgard/Documentation/#SEC_Installation:JwXc6VdkpeASgqbhxh8C), je vais y passer un peut de temps car elle semble répondre à mon dernier point!

**Comment by alhyss** [comment]
Bonjour,

Pour votre premier point, l'extension est utilisée sur les bases de production de plusieurs services de l'Etat, pour certains depuis l'été 2020. À ce stade, je dirais qu'elle n'est plus expérimentale. Impossible de garantir qu'il n'y aura pas de problème pour autant, mais notre intention était bien de mettre un outil fiable à disposition de nos services, donc elle est soigneusement testée. Nous avons aussi fait en sorte que le système reste souple, pour qu'il puisse facilement cohabiter avec d'autres formes de gestion des droits (cf. [doc](https://snum.scenari-community.org/Asgard/Documentation/#SEC_Compatibilite)), ce qui limite les impacts en cas d'installation/désinstallation.

Si vous installez l'extension et "référencez" tout ou partie des schémas de votre base, vous aurez deux conséquences automatiques directes : 
- à l'installation, la création des [rôles d'Asgard](https://snum.scenari-community.org/Asgard/Documentation/#SEC_RolesAsgard) ;
- lors du [référencement](https://snum.scenari-community.org/Asgard/Documentation/#SEC_Installation:JhD9L4PYtfbmNA2WOCcBO), l'[harmonisation des propriétaires des objets](https://snum.scenari-community.org/Asgard/Documentation/#SEC_Principes:ewUOBrobNQb52mIBFrqQJc) avec le propriétaire du schéma pour tous les schémas référencés.

Si vous avez dans l'idée d'utiliser Asgard pour du nettoyage et de le désinstaller ensuite, le second point peut être dérangeant si votre système de gestion des droits autorise voire a besoin que les propriétaires des schémas et des objets qui en dépendent soient différents. À mon avis, c'est le principal critère rédhibitoire.

L'autre contrainte assez significative est le fait qu'il n'est pas possible de référencer un schéma dont le propriétaire est un rôle de connexion (cf. [doc](https://snum.scenari-community.org/Asgard/Documentation/#SEC_Installation:w70IHh0ZYOfluzvOE4dIAf), ne concerne évidemment pas les super-utilisateurs). Si vous avez des schémas dans ce cas et souhaitez les conserver comme tels, cela peut être problématique.

À noter que pour votre sujet de réaffectation de droits vous n'auriez même pas besoin de référencer les schémas, ce qui lève dans ce cas les deux contraintes ci-avant. Selon son paramétrage, la fonction [asgard_reaffecte_role](https://snum.scenari-community.org/Asgard/Documentation/#CON_AsgardReaffecteRole) peut s'appliquer à tous les objets de la base.

La désinstallation de l'extension laisse en place tous les droits et n'a plus généralement pas d'autre effet que de supprimer tous les objets créés à l'installation de l'extension à l'exception des rôles (cf. [doc](https://snum.scenari-community.org/Asgard/Documentation/#SEC_Desinstallation)). Donc oui, même si nous n'avons pas vraiment développé l'extension dans cette optique, je pense qu'elle peut être adaptée à votre démarche, surtout si vous vous retrouvez dans ses grands principes : harmonisation des propriétaires, les rôles de connexion ne sont pas propriétaire des objets, droits homogènes sur un schéma (non obligatoire avec Asgard, mais si vous voulez faire autre chose, les utilitaires de l'extension ne serviront à rien), [profils](https://snum.scenari-community.org/Asgard/Documentation/#SEC_Principes:YemaEutjcXbLftrRBRLeKh) d'utilisateurs producteur / editeur / lecteur...

**Comment by MarHoff** [comment]
Merci pour toutes ces explications!

Clairement nos problématique semblent compatibles avec la philosophie d'ASGARD puisqu'elle sont:
- La réassignation des droits entre des rôles/groups mal pensés au départ et qu'on aimerais faire évoluer
- Une mise en cohérence des droits sur certains objets qui par manque de règles ou inattention sont actuellement associés à des rôles de connexion (utilisateurs nommés) ou des rôles/groups que l'on aimerais supprimer. Cela provoque des problèmes d'accès que l'on doit actuellement résoudre au cas par cas.
- Plus globalement avoir un cadre cohérent pour s'assurer de la sécurisation des données si on ouvre notre base à de nouveau utilisateurs ou de nouvelles applications

Après je pense que ça nécessitera beaucoup de tests pour vérifier qu'on a pas d'effet de bord, et bien appréhender la logique des profils d'utilisateurs mais votre programme à le mérite de fournir un cadre très clair et bien pensé auquel se rattacher.

La fonction `asgard_diagnostic()` est de ce point de vue intéressante puisque couplée à `asgard_initialise_obj()` et `asgard_initialise_schema()` elle permet une mise en place progressive et contrôlé.

Ce qui reste un peu nébuleux vu de l'extérieur c'est la logique en blocs/nomenclature qui semble vraiment répondre à votre logique interne, mais reste à priori optionnelle.  A vérifier notamment si des schéma existants et qui disposent d'un préfixe "z_" par exemple ne risquent pas de rentrer en collision avec cette logique lors d'une initialisation. 

Bravo encore pour ce projet et pour la doc très complète pour un projet aussi "jeune" 👍

**Comment by alhyss** [comment]
Merci !

Vous n'aurez pas de problème avec vos schémas pré-existants préfixés. Le seul cas où les mécanismes de l'extension ont un comportement différencié en fonction du préfixe est lorsque ce dernier est `d_`, ce qui correspond théoriquement à un schéma "[mis à la corbeille](https://snum.scenari-community.org/Asgard/Documentation/#SEC_SuppressionSchema)". La formule peut inquiéter, mais en pratique ça implique juste que ces schémas - et seulement ceux-là - peuvent être supprimés par un `UPDATE z_asgard.gestion_schema_usr SET creation = False` (sachant qu'un `DROP SCHEMA` marche dans tous les cas). Même s'ils n'ont pas vocation à être supprimés, disposer d'une méthode supplémentaire pour le faire ne semble pas très grave.

Du manière générale, il fallait que l'extension puisse être utilisée par nos services qui, comme vous, avait antérieurement un patrimoine de données, sans les forcer à renommer leurs schémas (d'autant que ce n'est souvent pas possible lorsqu'il y a des dépendances externes). La nomenclature et les blocs sont là parce que nous avons aussi des services qui sont en train de basculer des fichiers à plat à PostgreSQL, afin de les aider à structurer leurs bases.
