### ISSUE TITLE
Problème avec la suppression d'un schéma

### ISSUE THREAD

**Issue by thiegaillard** [MTES-MCT/asgard-postgresql#9]
Bonjour,

je viens de constater que si je **supprime un schéma** directement avec `pgadmin` (ou via sql), la table `z_asgard_admin.gestion_schema` ne se met pas à jour.
Il faut que j'aille supprimer la ligne directement dans la base

version Asgard installé dans ma base : 1.4.0

Merci d'avance pour votre aide.

**Comment by alhyss** [comment]
Bonjour @thiegaillard 

Lorsqu'un schéma est supprimé, son état - représenté par le champ `creation` de la table de gestion - passe automatiquement de `True` (actif) à `False` (inactif). La ligne reste, donc. Cela permet par exemple de restaurer un schéma sans perdre la configuration des droits. J'ai l'impression que c'est ce que tu décris et, si oui, c'est donc le fonctionnement normal.

Il est bien sûr possible de supprimer manuellement les lignes des schémas inactifs si elles ne sont plus utiles.

Tu trouveras plus de détails dans [cette partie](https://snum.scenari-community.org/Asgard/Documentation/co/SEC_SuppressionSchema.html) de la documentation si tu utilises Asgard avec pgAdmin. Avec AsgardManager, tu as une action [Effacer](https://snum.scenari-community.org/Asgard/Documentation/co/SEC_50_ActionsSchema.html), disponible uniquement sur les schémas inactifs, pour supprimer les lignes correspondantes de la table de gestion d'Asgard. L'action [Vider la corbeille](https://snum.scenari-community.org/Asgard/Documentation/co/SEC_60_ActionsBlocCorbeille.html) permet aussi d'effacer en une seule fois de la table de gestion tous les schémas qui ont été supprimés via la corbeille.

Est-ce que ça répond à ta question ?

**Comment by thiegaillard** [comment]
Ok, bien compris.
Nouveau serveur (bien plus puissant), nouvelle base, plugin Asgard et Plume : on va avoir une base nickel !

**Comment by alhyss** [comment]
Super nouvelle 🥳 
N'hésite pas si tu as d'autres questions !
